#!/usr/bin/python3
#+
# My second Nagios plugin -- check swap space.
#-

import argparse
import nagiosplugin

def load_meminfo() :
    "reads the contents of /proc/meminfo and returns a dict of the items found."
    result = {}
    for line in open("/proc/meminfo", "r") :
        items = line.split(":", 1)
        if len(items) == 2 :
            keyword, value = tuple(i.strip() for i in items)
            value = value.split(" ", 1)
            if len(value) > 1 :
                value, units = value
                assert units == "kB" # can’t handle anything else for now
            else :
                value = value[0]
            #end if
            result[keyword] = int(value)
        #end if
    #end line
    return \
        result
#end load_meminfo

class Swapfree(nagiosplugin.Resource) :

    def probe(self) :
        meminfo = load_meminfo()
        metrics = list \
          (
            nagiosplugin.Metric
              (
                name = k,
                value = round(100 * meminfo[k] / meminfo[j]),
                uom = "%"
              )
            for j, k in
                (
                    ("SwapTotal", "SwapFree"),
                )
          )
        return \
            metrics
    #end probe

#end Swapfree

def main() :
    parser = argparse.ArgumentParser(description = "check free swap space")
    for shortopt, longopt, kwargs in \
        (
            (
                "-w", "--warning",
                {
                    "metavar" : "RANGE",
                    "default" : 10,
                    "help" : "warn if percentage of available swap falls below this",
                },
            ),
            (
                "-c", "--critical",
                {
                    "metavar" : "RANGE",
                    "default" : 5,
                    "help" : "critical if percentage of available swap falls below this",
                },
            ),
            (
                "-v", "--verbose",
                {
                    "action" : "count",
                    "default" : 0,
                    "help" : "increase output verbosity",
                },
            ),
        ) \
    :
        parser.add_argument(shortopt, longopt, **kwargs)
    #end for
    args = parser.parse_args()
    nagiosplugin.Check \
      (
        Swapfree(),
        nagiosplugin.ScalarContext("SwapFree", "@%d" % int(args.warning), "@%d" % int(args.critical)),
        nagiosplugin.Summary()
      ).main(verbose = args.verbose)
#end main

if __name__ == "__main__" :
    main()
#end if
